spring:
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        descriptor:
          sql:
            BasicBinder: TRACE

  datasource:
    generate-unique-name: fale
    url: jdbc:h2:mem:testdb
